### ISSUE TITLE
Error in issue preview dropdown when using standard issue Pattern #(\d+)

### ISSUE THREAD

**Issue by rikbosch** [milgner/TeamCityRedmine#12]
![image](https://cloud.githubusercontent.com/assets/549975/4767140/985c8026-5b5a-11e4-9369-258e84872768.png)

Hi, when using the default pattern #(\d+) as ticket pattern, the issue tab works fine.
However, the issue preview popup does not work from the Changes tab.

p.s. using TC 8.1.4 (build 30168)

**Comment by milgner** [comment]
Yes, unfortunately that is an issue with TeamCity. I already reported it some time ago, feel free to vote for the ticket: https://youtrack.jetbrains.com/issue/TW-35477

**Comment by VladRassokhin** [comment]
It's fixed in TC 9.0
