### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by nheath** [milgner/TeamCityRedmine#5]
I've set up the redmine plugin and am having an authorization problem. Using the "Test Connection" button, I get the following error:

_Error: Failed to fetch issue details from "http://redmine-server/issues/123.xml", HTTP response code: 401 (Unauthorized)_

The integration itself partially works, where it properly parses the issue numbers and inserts links to the relevant issue, however when trying to fetch the .xml file for the issue popup, i get the above mentioned error. 

I'm using:
Teamcity  7.0.4 (build 21474)
Redmine 1.4.4

**Comment by milgner** [comment]
Does your Redmine installation support HTTP authentication?

I haven't really tested the plugin with recent versions of either Redmine or Teamcity for some time now. Although I wanted to upgrade my Teamcity installation to version 7 for some time, I already upgraded my Redmine to the 2.0 release.
So I'm not sure if a special plugin or server configuration is required for Redmine to support HTTP authentication.

Thanks for reporting this, however. I set it on my todo list for the upcoming weekend, when I will put together a TeamCity 7 release and test it with my Redmine 2.0.

**Comment by milgner** [comment]
Update: just found this plugin https://github.com/AdamLantos/redmine_http_auth - maybe try it and see if HTTP authentication works afterwards. I'll have a look at implementing authentication via REST token, too.

**Comment by nheath** [comment]
I don't have much information about our redmine server; another employee here set up and manages it. I sent him a message and will follow up with when I have more information available. It sounds like redmine HTTP authentication is required for this TC plugin to work? Is that correct?

It appears that our installation does NOT currently support this: if I log out so that i don't have a cookie/session and request an xml file directly, I get an http auth prompt, but it will not accept my credentials.

I noticed another issue you created regarding supporting auth via API tokens, and assume this is what you are referring to in your reply.This would be ideal, as it would mean I don't have to use personal redmine credentials or create an 'integration' redmine user. I have to assume that this is a non-trivial change, so In the meantime, if http auth is required, I can further investigate enabling this option via either the redmine plugin mentioned, or via an upgrade to redmine 2.0.

Many thanks for the help and responding quickly.

**Comment by milgner** [comment]
After updating my TeamCity to version 7 and finding that the module still compiles and thus should be fully compatible, I found a section in the Redmine documentation regarding authentication which reads `[...] using your API key [...] passed in as a username with a random password via HTTP Basic authentication`
Could you maybe try that combination?
Apparently they also introduced a "X-Redmine-API-Key" HTTP header in version 1.1.0 - I'll have a look at the API and infrastructure in the provider and see if I can put together support for this - it's probably the most straightforward solution.

**Comment by milgner** [comment]
After a little bit of trouble with my TeamCity installation I now adapted the plugin to use the API access token.
Yet you'd still have to use your personal token or a separate integration user, because apparently that's the way Redmine implements the user retrieval in application_controller.rb.
I'd have to do some more digging into the Redmine source to find out how (or if) the API token configured under "Settings - incoming emails" can be used for this.

**Comment by nheath** [comment]
I just wanted to follow up here and let you know that the switch to API tokens fixed my authentication issue. Thanks!
Unfortunately, I now have a different issue, which I'll create as a new thread.
