### ISSUE TITLE
Error: wrong class use

### ISSUE THREAD

**Issue by ferdyh** [milgner/TeamCityRedmine#7]
When i hit test connection when adding the issue tracker i get  following error: Error: wrong class use

I use teamcity 7.1.1 and redmine 2.1.2

Host: https://ticket.company.com/
Api: user api key
Ticket pattern: #(\d+)

**Comment by minneyar** [comment]
I ran into this same issue a little while ago.  In the source code, if you look at file RedmineIssueFetcher.java, at line 61 there's a statement which creates an HttpURL object.  This will throw an exception if you enter an HTTPS URL.

One solution for this is to use HTTP instead, but the line in the source code is actually useless, so you can also remove it, recompile, and your HTTPS URL will work fine.

**Comment by milgner** [comment]
Finally got around to fixing the SSL-related problems. See the new release, v1.2, I provided a prebuilt .jar as well.
